const mongoose=require('mongoose');
const Customer=mongoose.model('Customer',{
    image:{
        type:String,
        default:"no-photo.jpg",
    },
    fullname:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    phone:{
        type:String,
    },
    address:{
        type:String,
    },
    companyname:{
        type:String
    },
    bio:{
        type:String
    },
    website:{
        type:String
    },
    instagram:{
        type:String
    },
    facebook:{
        type:String
    },
    youtube:{
        type:String
    },
    twitter:{
        type:String
    },
    password:{
        type:String,
        required:true,
       minlegth:8
    },
    resetLink:{
        data:String,
        default:""
    }
  
})
module.exports=Customer;